apiVersion: v1
kind: Service
metadata:
  name: pow-node
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
  selector:
    app: pow-node