apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-db
  template:
    metadata:
      labels:
        app: system-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: "blockchain"

          image: mongo
          imagePullPolicy: IfNotPresent
          name: system-db
          ports:
            - containerPort: 27017