apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-pow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-pow
  template:
    metadata:
      labels:
        app: system-pow
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: "system-db"
          image: bogdannaida/system-pow
          name: system-pow
          ports:
            -
              containerPort: 8080